### ISSUE TITLE
Sentences not reflecting errors correctly

### ISSUE THREAD

**Issue by longrunningprocess** [presciencelabs/tabitha-editor#122]
# from Richard

> "David killed." and "David threw." should generate errors.

> I don't think there should be any errors in these sentences: "For [God says false things] is-V not possible. God did those things [so-that we(people) _incl [ _descriptive who have gone to God _implicit [in order to be safe]] would continue to hope [God will complete/fulfill God's promise for us(people) _incl]]."

**Comment by craigp-atw** [comment]
These have already been resolved
