### ISSUE TITLE
various suggestions with backtranslation

### ISSUE THREAD

**Issue by longrunningprocess** [presciencelabs/tabitha-editor#23]
from Richard:

Change "_paragraph" to "(paragraph)". (resolved in #54 )

Put relative clauses modifying a proper noun (level 4 word) or starting with "_ descriptive" within parentheses, like "John, who was with Mary, went to Bethlehem."
- '_ descriptive' clauses resolved in #54 

2,3,4... -> two, three, four... (resolved in #54 )

Tribe//region//city//country named Y -> X of Y (resolved in #54 )

God's book -> the Scriptures (resolved in #54 )

Any comment starting with "_ " and containing "implicit" and " necessary" is treated like "_  implicitNecessary", and any comment with "_ " and containing "implicit" but not "necessary" is treated like "_implicit". (Right now combinations of words in comments don't work.)

**Comment by craigp-atw** [comment]
Also from Richard: "servant's/deacon's" doesn't work in the editor

It should remove "servant's/" from the pairing and just be left with "deacon's". The apostrophe is throwing off the regex that deals with pairings.

![image](https://github.com/presciencelabs/tabitha-editor/assets/152427351/585b1dfe-8c02-4724-abde-756aa1571342)
