### ISSUE TITLE
handle words with multiple complexity levels

### ISSUE THREAD

**Issue by longrunningprocess** [presciencelabs/tabitha-editor#31]
the editor currently tries to determine a word's complexity level but some words can have multiple levels even with the same part of speech

<img width="1384" alt="image" src="https://github.com/presciencelabs/tabitha-editor/assets/4412848/833a9664-a1e4-46cf-ab32-592f0d700a4c">

![image](https://github.com/presciencelabs/tabitha-editor/assets/4412848/da080d70-2f91-4bab-a4b8-0b06177cb972)

**Comment by craigp-atw** [comment]
I plan to add a 'suggest' field on a token, which will show an icon/message, but not cause the verse to fail as a whole. After all the rules are executed, if there are still multiple levels as possibilities, show a 'suggest' as a warning to the user. Maybe suggest the user adds a sense marker on the word to disambiguate.
