### ISSUE TITLE
automate the extraction of "word forms" from TBTA

### ISSUE THREAD

**Issue by longrunningprocess** [presciencelabs/tabitha-editor#32]
currently, word forms are being extracted from TBTA manually and then transformed and loaded into a database via scripts in `tabitha-editor/database/inflections`.

Would like to see this automated:

- headless script to run TBTA and push the right buttons?
- provide ability to do this via a command line option to TBTA?
- add functionality to TBTA that will write the forms out into a database or file whenever they change?
- other possibilities?

**Comment by craigp-atw** [comment]
Related to https://github.com/presciencelabs/tabitha-ontology/issues/35 , we should relocate the inflection database to the `target` app.

**Comment by craigp-atw** [comment]
Created an issue in the targets repo instead.
