### ISSUE TITLE
"each-other(bodies)" not working properly

### ISSUE THREAD

**Issue by longrunningprocess** [presciencelabs/tabitha-editor#36]
# reported by Richard

![image](https://github.com/presciencelabs/tabitha-editor/assets/4412848/87571522-d2f4-46fe-abe7-b807c518b5eb)

**Comment by craigp-atw** [comment]
The regex EXTRACT_PRONOUN_REFERENT needs to handle a hyphen before the parenthesis. \w does not cover that. There probably doesn't need to be any restriction to the character at that point.
