### ISSUE TITLE
some pairings not being handled properly

### ISSUE THREAD

**Issue by longrunningprocess** [presciencelabs/tabitha-editor#40]
# Reported by Sarah

`A yard courtyard yard/courtyard.`

![image](https://github.com/presciencelabs/tabitha-editor/assets/4412848/517f2fd7-69bf-43a4-8f92-ba1ecb605ecb)

**Comment by longrunningprocess** [comment]
`A gifts sacrifices gifts/sacrifices.`

![image](https://github.com/presciencelabs/tabitha-editor/assets/4412848/7c0fba0a-7c4a-43da-bb1e-c88380cb5630)

**Comment by craigp-atw** [comment]
Turns out no pairings are showing properly. Must be an issue from the earlier tokenization expansion.
