### ISSUE TITLE
Adjectives like 'satisfied' or 'pleased' are not getting recognized

### ISSUE THREAD

**Issue by craigp-atw** [presciencelabs/tabitha-editor#45]
These Adjectives correspond to the past participle of a Verb. The Adjective is not found in the form lookup, so the editor thinks it's only the Verb. This causes issues with the 'agent of a passive' check where it should not be applied.

![image](https://github.com/presciencelabs/tabitha-editor/assets/152427351/6e8faa53-021f-41cb-8f99-f920bc93dae8)

This is an issue related to #16 - We should actually keep the stems that have spaces in the inflections so that the stem can be found in the form lookup. The stems with spaces should remain filtered out though.

**Comment by longrunningprocess** [comment]
![image](https://github.com/presciencelabs/tabitha-editor/assets/4412848/c5b82aa2-fa64-43eb-b982-dc9f665a2a01)
