### ISSUE TITLE
Store json-based rules in the database

### ISSUE THREAD

**Issue by craigp-atw** [presciencelabs/tabitha-editor#48]
Currently the rules are hard-coded json objects. But we want to move them to the database so that we/the user can add new ones without rebuilding and deploying.

**Comment by longrunningprocess** [comment]
#49 probably needs to be done first.

**Comment by craigp-atw** [comment]
This needs to wait until we have user authentication in place to be able to update the db through the app itself. Until that happens, it's easier to keep them all hard-coded.

**Comment by craigp-atw** [comment]
We're thinking this is no longer necessary or helpful. If it proves advantageous later, we can reopen.
