### ISSUE TITLE
False negatives

### ISSUE THREAD

**Issue by longrunningprocess** [presciencelabs/tabitha-editor#57]
# from Tatyana

<img width="985" alt="image" src="https://github.com/presciencelabs/tabitha-editor/assets/4412848/d8c4ee7d-9e01-4a29-8b1d-baee19a25432">

> There is an issue that editor sees as an error - the condition of verb "continue to..." which should not have brackets between "continue" and the verb it influences. 
The same issue with Continuous Tense "is +verb" it flags as 2 verbs without bracket in-between = error

<img width="945" alt="image" src="https://github.com/presciencelabs/tabitha-editor/assets/4412848/167b165b-3e77-4dc9-a379-98ebf505bc08">

<img width="739" alt="image" src="https://github.com/presciencelabs/tabitha-editor/assets/4412848/e2128fee-cb08-48a6-9eb5-b678c39765cf">

> Also it flags "named" as a separate verb, but I am not sure how you can fix this one, as sometimes it is a feature, and sometimes it is an actual verb.

# from Huey

<img width="1122" alt="image" src="https://github.com/presciencelabs/tabitha-editor/assets/4412848/0021bf9a-1d62-4ae9-b290-66b256b5f53b">

# from Richard

<img width="1401" alt="image" src="https://github.com/presciencelabs/tabitha-editor/assets/4412848/5e00a35c-a3ef-4d71-82a2-1976dcf75a72">

> Several things that are marked here as errors when they shouldn't be.

**Comment by craigp-atw** [comment]
Fixed in #59
