### ISSUE TITLE
Wording change from "explication" to "suggestion" under certain circumstances.

### ISSUE THREAD

**Issue by longrunningprocess** [presciencelabs/tabitha-editor#79]
# from Richard

Second, although the information about a suggestion for a word that is not in the ontology but in the "How to" is put in the "explication" column of the "How-to", it's not really an explication. If it's not too much trouble, I would change the wording to "Suggestion".

**Comment by craigp-atw** [comment]
We just need to change the heading within the `NotFound.svelte` file
