### ISSUE TITLE
Warn when a complex alternate is not followed by a simple alternate

### ISSUE THREAD

**Issue by longrunningprocess** [presciencelabs/tabitha-editor#80]
# from Richard

Third, one thing we talked about in another meeting was possibly adding a warning if a verse had a complex alternate that wasn't followed by a simple alternate. It's not possible to say that that's always an error, so it should be a warning.

**Comment by longrunningprocess** [comment]
ok, I'm going to close this then.  We can address it when it comes up.

**Comment by craigp-atw** [comment]
Reopening and renaming for adding the check for if a complex alternate is not immediately followed by a simple alternate.
